# Generated by Django 5.2.7 on 2025-11-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_surveysubmission_surveyanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
